# Generated by Django 4.2.19 on 2025-03-03 19:02

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заглавие')),
                ('content', models.TextField(verbose_name='Съдържание')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('published', models.DateField(default=datetime.date.today, verbose_name='Публикувано на')),
            ],
            options={
                'verbose_name': 'Статия',
                'verbose_name_plural': 'Статии',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='име')),
                ('email', models.EmailField(blank=True, max_length=200, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=200, verbose_name='телефон')),
                ('message', models.TextField(verbose_name='съобщение')),
                ('published', models.DateField(default=django.utils.timezone.now, verbose_name='Дата/час на получаване')),
            ],
            options={
                'verbose_name': 'Съобщение',
                'verbose_name_plural': 'Съобщения',
            },
        ),
    ]
