# Generated by Django 4.2.19 on 2025-03-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Снимка'),
        ),
    ]
